version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    environment:
      - BUNDLE_PATH=/bundle
      - SPROCKETS_CACHE=/cache
    volumes:
      - .:/app
      - bundle:/bundle
      - cache:/cache
    stdin_open: true
    tty: true

volumes:
  cache:
  bundle:
